server:
  port: 8081


spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/HumanResources'
    username: 'postgres'
    password: 'Nic3993.'
    driver-class-name: org.postgresql.Driver

#spring:
#  datasource:
#    url: 'jdbc:postgresql://postgresql-20221109164148.postgres.database.azure.com:5432/azure_sys?useSSL=true&requireSSL=false'
#    username: 'team3@postgresql-20221109164148'
#    password: '10101010kk..'
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
