server:
  port: 8081


#spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/HumanResources'
#    username: 'postgres'
#    password: 'Nic3993.'
#    driver-class-name: org.postgresql.Driver

spring:
  datasource:
    url: 'jdbc:postgresql://humanresourcest3.postgres.database.azure.com:5432/azure_sys?useSSL=true&requireSSL=false'
    username: 'team3@humanresourcest3'
    password: '10101010kk..'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
