server:
  port: ${admin_port}

#server:
#  port: 8081

#spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/HumanResources'
#    username: 'postgres'
#    password: 'Nic3993.'
#    driver-class-name: org.postgresql.Driver


spring:
  datasource:
    url: ${db_postgresql_url}
    username: ${db_postgresql_username}
    password: ${db_postgresql_password}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: 'team3-hrproject@outlook.com'
    password: '10101010Kk..'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


