apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-admin
spec:
  selector:    
    app: admin-service
  type: LoadBalancer
  ports:
    - name: admin-service
      port: 8081
      targetPort: 8081